# Generated by Django 2.1.1 on 2018-10-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.CharField(default='All', max_length=140),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_urls',
            field=models.TextField(max_length=240),
        ),
    ]
